config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'todos#index'
  resources 'todos'
  resources 'categories'
  get '/todos/new' => 'todos#new'
  get '/todos/notebooks' => 'todos#notebooks'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :todos
  belongs_to :user

  validates_presence_of :user_id, :title, :color
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates_presence_of :user_id, :category_id, :title, :body, :due_date
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(cat_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to todos_path, notice: "Category Created"
    else
      redirect_to :back, notice: "Error Creating Category"
    end
  end

  private

  def cat_params
    params.require(:category).permit!
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = current_user.todos
    @new_todo = Todo.new
  end

  def new
    @new_todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    if @todo.save
      redirect_to todos_path, notice: "Todo Created"
    else
      redirect_to :back, notice: "Aw snap, error saving Todo"
    end
  end

  def notebooks

  end

  def show

  end

  private

  def todo_params
    params.require(:todo).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/categories/new.html.erb
<h1>Create a New Category</h1>

<div class="create-category">
  <%= simple_form_for @category do |f| %>
    <%= f.input :title %>
    <%= f.input :color %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>TodoTodos</title>

	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

	  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

	</head>
	<body>

		<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ToDos</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <!-- <li><a href="/todos/new">New Todo</a></a></li> -->
						<li>
							<%= link_to "New Category", new_category_path, method: "get" %>
						</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Default</a></li>
						<% if current_user %>
							<li>
								<%= link_to "Log Out", destroy_user_session_path, method: "delete" %>
							</li>
						<% else %>
							<li>
								<%= link_to "Log In", new_user_session_path, method: "get" %>
							</li>
						<% end %>
	          <li><a href="#">Fixed</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

	<div class="container col-md-10 col-md-offset-1">

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>

	</div>

	</body>

	<footer>

		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

	</footer>
</html>

app/views/todos/index.html.erb
<h2>Your Todos</h2>

<div class="crreate-todo row">

  <%= simple_form_for @new_todo do |f| %>
    <div class="col-md-8">
      <%= f.input :title %>
      <%= f.input :body %>
    </div>
    <div class="col-md-4">
      <%= f.association :category, prompt: "Choose a Notebook", html5: true %>
      <%= f.input :due_date, as: :date, html5: true %>
    </div>
    <div class="col-md-12">
      <%= f.button :submit, class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>
<h2>Todos</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Due Date</th>
      <th>Complete?</th>
      <th>Notebook</th>
    </tr>
  </thead>
  <% @todos.each do |t| %>
    <% if t.category.color %>
      <tr style="background-color : <%= t.category.color %>;">
    <% else %>
      <tr>
    <% end %>
        <td><%= t.title%></td>
        <td><%= t.due_date%></td>
        <td><%= t.complete%></td>
        <td><%= t.category.title %></td>
    </tr>
  <% end %>

</table>

app/views/todos/new.html.erb
<h1>Create a Todo</h1>
<div class="create-todo">
  <%= simple_form_for @new_todo do |f| %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.association :category, prompt: "Choose a Notebook" %>
    <%= f.input :due_date, as: :date, html5: true %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/todos/notebooks.html.haml
%html
  %body
    %h1 The Best!

app/views/todos/show.html.haml
.h1 This is a test